### ISSUE TITLE
Ignoring comparisons using an attribute

### ISSUE THREAD

**Issue by serhatzor** [kbilsted/ReassureTest.Net#3]
You can add an attribute and then we can use this attribute in our fields to ignore comparisons.

**Comment by kbilsted** [comment]
That will be very easy to do, what name should we make the attribute?  `[Ignore]` is nice I think, but it can be confused with the `[Ignore]` of nunit, mstest, ... that use it for a different purpose. And perhaps it's not a problem..

**Comment by serhatzor** [comment]
"With" extension method is very good to ignore fields. For instance, I am using model classes in my test cases and I think that adding an attribute into this models from a testing framework is a good practice. Because the code base should not know any thing about test cases.
