### ISSUE TITLE
Fluent builders to configure  object graph equation function

### ISSUE THREAD

**Issue by serhatzor** [kbilsted/ReassureTest.Net#4]
A fluent builder would be nice to configure your object graph equation function.

**Comment by kbilsted** [comment]
Thanks for the suggestion. Can you give an example of what you mean, and what the advantages of using a builder is?

**Comment by serhatzor** [comment]
I need to ignore some fields in some test cases not globally. "With" extension and your example is enough for me .

var cfg = Reassure.DefaultConfiguration.DeepClone();
cfg.Harvesting.FieldValueSelectors.Add((o, pi) => pi.Name.StartsWith("S"));

someObject.With(cfg).Is("{ StartTime = ... StopTime = ... }");
