### ISSUE TITLE
Is there StatePrinter yet?

### ISSUE THREAD

**Issue by dan-oak** [kbilsted/ReassureTest.Net#9]
Hi, StatePrinter Readme states:

> THIS PROJECT IS BEING SUPERSEDED BY ReassureTest! GO TO https://github.com/kbilsted/ReassureTest.Net

But I don't see the class in this library yet. Do you have an ETA?

**Comment by kbilsted** [comment]
Hi Dan
Thanks for reaching out. I'm not sure what you mean. ReassureTest is the next generation of stateprinter.. it has its own name and project.

Out of curiosity, what/how do you use stateprinter?

**Comment by dan-oak** [comment]
Honestly I didn't even know StatePrinter has something to do with testing at first and so far I'm just:
```c#
public override String ToString() => return Printer.PrintObject(this);
```
😄 

But now after actually reading the readme I found this project and also got interested in your vision on the assertions. I think it's cool and worth trying it out, but after installing ReassureTest i just was expecting StatePrinter in it as well. Maybe you don't have an intention to move it here, I don't know. Let me know. 
And yeah, probably I don't use the StatePrinter for it's intended use in the first place? :)

**Comment by kbilsted** [comment]
Nah, any usage is cool by me :-)

I'm not sure what I need stateprinter for in Reassure.Net - but they are similar in that they print the underlying graph. It would be very easy to make a `PrintObject` in Reasurre.Net

**Comment by kbilsted** [comment]
If you like the ideas of testing differently, please do go ahead and try it out. I'm always interested in hearing your experiences and feedback & questions..

**Comment by dan-oak** [comment]
Okay! Thanks for your responses. I'll give feedback when I'll try it out. Good luck )
